name: VDSM
on:
  workflow_dispatch:

jobs:
  dsm:
    name: dsm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Virtual DSM
        id: vdsm
        uses: synology-community/virtual-dsm-action@main
        with:
          disk-size: "6G"
